package com.local.focusfence.ui;
import android.app.*;import android.content.*;import android.content.pm.*;import android.graphics.Typeface;import android.os.Bundle;import android.provider.Settings;import android.text.InputType;import android.widget.*;import com.local.focusfence.storage.Prefs;import com.local.focusfence.util.*;import java.util.*;
public final class MainActivity extends Activity{
 private Prefs p; private LinearLayout root;
 static final class A{final String l,pkg;A(String l,String p){this.l=l;pkg=p;}public String toString(){return l+"\n"+pkg;}}
 protected void onCreate(Bundle b){super.onCreate(b);p=new Prefs(this);ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(36));s.addView(root);setContentView(s);}
 protected void onResume(){super.onResume();render();}
 private void render(){root.removeAllViews();txt("FocusFence 0.1.1",30,true);txt("Blocage local: jeux, horaires, Reels / Stories / Shorts.",15,false);
 sec("Autorisations");boolean a=PermissionUtils.isAccessibilityEnabled(this),u=PermissionUtils.hasUsageAccess(this);txt("Accessibilité: "+(a?"ACTIF":"À ACTIVER"),16,a);Button ab=btn("Réglages accessibilité");ab.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));root.addView(ab);txt("Données d'utilisation: "+(u?"ACTIF":"À ACTIVER"),16,u);Button ub=btn("Autoriser données d'utilisation");ub.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS)));root.addView(ub);if(!u)txt("Sans cet accès, les quotas Jeux ne peuvent pas être calculés.",13,true);
 sec("Reels / Stories / Shorts");CheckBox en=new CheckBox(this);en.setText("Activer le quota commun");en.setChecked(p.shortEnabled());root.addView(en);EditText lim=num(p.shortLimitMinutes());lab("Minutes/jour (0 = illimité)",lim);CheckBox st=new CheckBox(this);st.setText("Inclure Instagram + Facebook Stories");st.setChecked(p.includeStories());root.addView(st);int[] ss={p.shortStartMinute()},se={p.shortEndMinute()};root.addView(time("Début autorisé",ss));root.addView(time("Fin autorisée",se));Button sv=btn("Enregistrer contenus courts");sv.setOnClickListener(v->{p.setShortEnabled(en.isChecked());p.setShortLimitMinutes(parse(lim,20));p.setIncludeStories(st.isChecked());p.setShortStartMinute(ss[0]);p.setShortEndMinute(se[0]);toast();});root.addView(sv);txt("Utilisé aujourd'hui: "+dur(p.shortUsageMs()),14,false);
 sec("Groupe Jeux");CheckBox ge=new CheckBox(this);ge.setText("Activer le groupe Jeux");ge.setChecked(p.gamesEnabled());root.addView(ge);EditText gl=num(p.gamesLimitMinutes());lab("Minutes cumulées/jour",gl);int[] gs={p.gamesStartMinute()},gg={p.gamesEndMinute()};root.addView(time("Début autorisé",gs));root.addView(time("Fin autorisée",gg));txt(p.gamePackages().size()+" application(s) sélectionnée(s)",14,false);Button ch=btn("Choisir les applications");ch.setOnClickListener(v->choose());root.addView(ch);Button sg=btn("Enregistrer groupe Jeux");sg.setOnClickListener(v->{p.setGamesEnabled(ge.isChecked());p.setGamesLimitMinutes(parse(gl,60));p.setGamesStartMinute(gs[0]);p.setGamesEndMinute(gg[0]);toast();});root.addView(sg);
 sec("Diagnostic");CheckBox d=new CheckBox(this);d.setText("Mode calibration Logcat");d.setChecked(p.diagnosticMode());d.setOnCheckedChangeListener((b,c)->p.setDiagnosticMode(c));root.addView(d);}
 private void choose(){List<A> as=apps();String[] ls=new String[as.size()];boolean[] ck=new boolean[as.size()];Set<String>s=new LinkedHashSet<>(p.gamePackages());for(int i=0;i<as.size();i++){ls[i]=as.get(i).toString();ck[i]=s.contains(as.get(i).pkg);}new AlertDialog.Builder(this).setTitle("Applications du groupe Jeux").setMultiChoiceItems(ls,ck,(d,i,c)->{if(c)s.add(as.get(i).pkg);else s.remove(as.get(i).pkg);}).setPositiveButton("Enregistrer",(d,w)->{p.setGamePackages(s);render();}).setNegativeButton("Annuler",null).show();}
 private List<A> apps(){PackageManager pm=getPackageManager();Intent q=new Intent(Intent.ACTION_MAIN);q.addCategory(Intent.CATEGORY_LAUNCHER);List<A>o=new ArrayList<>();Set<String>s=new HashSet<>();for(ResolveInfo r:pm.queryIntentActivities(q,PackageManager.MATCH_ALL)){if(r.activityInfo==null)continue;String pkg=r.activityInfo.packageName;if(pkg.equals(getPackageName())||!s.add(pkg))continue;CharSequence l=r.loadLabel(pm);o.add(new A(l==null?pkg:l.toString(),pkg));}Collections.sort(o,Comparator.comparing(x->x.l.toLowerCase(Locale.ROOT)));return o;}
 private Button time(String pre,int[] h){Button b=btn(pre+": "+TimeUtils.formatMinute(h[0]));b.setOnClickListener(v->new TimePickerDialog(this,(x,hh,m)->{h[0]=hh*60+m;b.setText(pre+": "+TimeUtils.formatMinute(h[0]));},h[0]/60,h[0]%60,true).show());return b;}
 private EditText num(int v){EditText e=new EditText(this);e.setInputType(InputType.TYPE_CLASS_NUMBER);e.setText(String.valueOf(v));return e;}private int parse(EditText e,int f){try{return Math.max(0,Integer.parseInt(e.getText().toString()));}catch(Exception x){return f;}}
 private void lab(String s,EditText e){txt(s,13,false);root.addView(e);}private Button btn(String s){Button b=new Button(this);b.setText(s);return b;}private void sec(String s){TextView t=txt(s,21,true);t.setPadding(0,dp(24),0,dp(6));}private TextView txt(String s,int z,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(t);return t;}private void toast(){Toast.makeText(this,"Réglages enregistrés",Toast.LENGTH_SHORT).show();}private String dur(long ms){long q=Math.max(0,ms)/1000;return(q/60)+" min "+(q%60)+" s";}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}